export const RouteEnum = {
  HOME: "/",
  // DASHBOARD: "/",
  LOGIN: "/login",
  SIGNUP: "/complete-signUp",
  DASHBOARD: "/dashboard",
  SIGNUPCLIENT: "/signup-client",
  MANAGE_COMPANIES: "/manage-companies",
  MANAGE_RIDERS: "/manage-riders",
  SALES_REPORT: "/manage-riders/sales",

  TRIPS: "/trips",
  MAPS: "/maps",
  SUPPORT: "/support",
  LIST_OF_MEDICINES: "/list-of-medicines",
  LIST_OF_MEDICINES_INNER: "/list-of-medicines/azthral",
  MEDICINE_GROUPS: "/medicine-groups",
  DISPENSER: "/dispenser",
  PATIENT: "/patient",
};
